In [1]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [14]:
import pandas as pd

file_path = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"

xls = pd.ExcelFile(file_path)
print("Sheet names:", xls.sheet_names)

Sheet names: ['ethiopia_fi_unified_data', 'Impact_sheet']

In [1]:
import pandas as pd

file_path = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"

# Load Excel file
xls = pd.ExcelFile(file_path)

# Print all sheet names
print("Sheet names in the file:", xls.sheet_names)

Sheet names in the file: ['ethiopia_fi_unified_data', 'Impact_sheet']

In [2]:
import pandas as pd

file_path = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"

# Load the Excel file
xls = pd.ExcelFile(file_path)

# Print all sheet names
print("Sheets in this Excel file:", xls.sheet_names)

Sheets in this Excel file: ['ethiopia_fi_unified_data', 'Impact_sheet']

In [4]:
import pandas as pd

file_path = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"

# Load the Excel workbook
xls = pd.ExcelFile(file_path)

# Print the sheet names
print("Sheets in this Excel file:", xls.sheet_names)

Sheets in this Excel file: ['ethiopia_fi_unified_data', 'Impact_sheet']

In [6]:
import pandas as pd

# Full path to your Excel file
file_path = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"

# Step 1: Check what sheets exist in the file
xls = pd.ExcelFile(file_path)
print("Sheets inside the Excel file:", xls.sheet_names)

# Step 2: Once you know the sheet names, replace these placeholders
# Example: if the print output shows ['data_sheet', 'impact_sheet'], use those exact names
data_sheet_name = xls.sheet_names[0]       # pick the first sheet (replace if needed)
impact_links_sheet_name = xls.sheet_names[1]  # pick the second sheet (replace if needed)

# Load the sheets into DataFrames
data = pd.read_excel(file_path, sheet_name=data_sheet_name)
impact_links = pd.read_excel(file_path, sheet_name=impact_links_sheet_name)

# Load reference codes
refs = pd.read_excel(r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\reference_codes.xlsx")

# Confirm loading
print("Data shape:", data.shape)
print("Impact links shape:", impact_links.shape)
print("Reference codes shape:", refs.shape)

# Preview first few rows
display(data.head())
display(impact_links.head())
display(refs.head())

Sheets inside the Excel file: ['ethiopia_fi_unified_data', 'Impact_sheet']
Data shape: (43, 34)
Impact links shape: (14, 35)
Reference codes shape: (71, 4)

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

,record_id,parent_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,IMP_0001,EVT_0001,impact_link,NaN,ACCESS,Telebirr effect on Account Ownership,NaN,NaN,15.0,NaN,...,increase,high,15.0,12,literature,Kenya,Example_Trainee,2025-01-20,NaN,Kenya M-Pesa showed +20pp over 5 years
1,IMP_0002,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on Telebirr Users,NaN,NaN,NaN,NaN,...,increase,high,NaN,3,empirical,NaN,Example_Trainee,2025-01-20,NaN,Direct subscriber acquisition
2,IMP_0003,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on P2P Transactions,NaN,NaN,25.0,NaN,...,increase,high,25.0,6,empirical,NaN,Example_Trainee,2025-01-20,NaN,New digital payment channel
3,IMP_0004,EVT_0002,impact_link,NaN,ACCESS,Safaricom effect on 4G Coverage,NaN,NaN,15.0,NaN,...,increase,medium,15.0,12,empirical,NaN,Example_Trainee,2025-01-20,NaN,Network investment from competition
4,IMP_0005,EVT_0002,impact_link,NaN,AFFORDABILITY,Safaricom effect on Data Affordability,NaN,NaN,-20.0,NaN,...,decrease,medium,-20.0,12,literature,Rwanda,Example_Trainee,2025-01-20,NaN,Competition typically reduces prices

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All

In [2]:
import pandas as pd

# Paths
main_file = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"
ref_file = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\reference_codes.xlsx"

# Load Excel
xls = pd.ExcelFile(main_file)
print("Sheets:", xls.sheet_names)

# Load sheets (this assumes first = data, second = impact_links)
data = pd.read_excel(main_file, sheet_name=xls.sheet_names[0])
impact_links = pd.read_excel(main_file, sheet_name=xls.sheet_names[1])

# Load reference codes
refs = pd.read_excel(ref_file)

print("Loaded successfully")

Sheets: ['ethiopia_fi_unified_data', 'Impact_sheet']
Loaded successfully

In [3]:
# Basic dataset info
data.info()

# Count records by record_type
data['record_type'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            43 non-null     object
 1   record_type          43 non-null     object
 2   category             10 non-null     object
 3   pillar               33 non-null     object
 4   indicator            43 non-null     object
 5   indicator_code       43 non-null     object
 6   indicator_direction  33 non-null     object
 7   value_numeric        33 non-null     float64
 8   value_text           10 non-null     object
 9   value_type           43 non-null     object
 10  unit                 33 non-null     object
 11  observation_date     43 non-null     datetime64[ns]
 12  period_start         10 non-null     datetime64[ns]
 13  period_end           10 non-null     datetime64[ns]
 14  fiscal_year          43 non-null     object
 15  gender               43 non-null     object
 16  location             43 non-null     object
 17  region               0 non-null      float64
 18  source_name          43 non-null     object
 19  source_type          43 non-null     object
 20  source_url           31 non-null     object
 21  confidence           43 non-null     object
 22  related_indicator    0 non-null      float64
 23  relationship_type    0 non-null      float64
 24  impact_direction     0 non-null      float64
 25  impact_magnitude     0 non-null      float64
 26  impact_estimate      0 non-null      float64
 27  lag_months           0 non-null      float64
 28  evidence_basis       0 non-null      float64
 29  comparable_country   43 non-null     object
 30  collected_by         43 non-null     datetime64[ns]
 31  collection_date      10 non-null     object
 32  original_text        33 non-null     object
 33  notes                0 non-null      float64
dtypes: datetime64[ns](4), float64(10), object(20)
memory usage: 11.6+ KB

record_type
observation    30
event          10
target          3
Name: count, dtype: int64

# Task 1 – Data Exploration & Enrichment

⚠️ Always run the data loading cell before any analysis

In [4]:
# Pillar distribution
data['pillar'].value_counts(dropna=False)

# Source types
data['source_type'].value_counts()

# Confidence levels
data['confidence'].value_counts()

confidence
high      40
medium     3
Name: count, dtype: int64

In [5]:
# Unique indicators
indicators = data['indicator_code'].unique()
len(indicators), indicators

(29,
 array(['ACC_OWNERSHIP', 'ACC_MM_ACCOUNT', 'ACC_4G_COV', 'ACC_MOBILE_PEN',
        'ACC_FAYDA', 'USG_P2P_COUNT', 'USG_P2P_VALUE', 'USG_ATM_COUNT',
        'USG_ATM_VALUE', 'USG_CROSSOVER', 'USG_TELEBIRR_USERS',
        'USG_TELEBIRR_VALUE', 'USG_MPESA_USERS', 'USG_MPESA_ACTIVE',
        'USG_ACTIVE_RATE', 'AFF_DATA_INCOME', 'GEN_GAP_ACC',
        'GEN_MM_SHARE', 'GEN_GAP_MOBILE', 'EVT_TELEBIRR', 'EVT_SAFARICOM',
        'EVT_MPESA', 'EVT_FAYDA', 'EVT_FX_REFORM', 'EVT_CROSSOVER',
        'EVT_MPESA_INTEROP', 'EVT_ETHIOPAY', 'EVT_NFIS2',
        'EVT_SAFCOM_PRICE'], dtype=object))

In [6]:
# Convert date column (safe)
data['observation_date'] = pd.to_datetime(data['observation_date'], errors='coerce')

# Date range
data['observation_date'].min(), data['observation_date'].max()

(Timestamp('2014-12-31 00:00:00'), Timestamp('2030-12-31 00:00:00'))

In [7]:
events = data[data['record_type'] == 'event']

events[['category', 'observation_date', 'source_name']].sort_values('observation_date').head(10)

          category observation_date    source_name
33  product_launch       2021-05-17  Ethio Telecom
41          policy       2021-09-01            NBE
34    market_entry       2022-08-01           News
35  product_launch       2023-08-01      Safaricom
36  infrastructure       2024-01-01           NIDP
37          policy       2024-07-29            NBE
38       milestone       2024-10-01      EthSwitch
39     partnership       2025-10-27      EthSwitch
42         pricing       2025-12-15           News
40  infrastructure       2025-12-18  NBE/EthSwitch

In [10]:
impact_links.info()
display(impact_links.head())
impact_links[['parent_id', 'pillar', 'related_indicator', 'impact_direction', 'lag_months']].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            14 non-null     object
 1   parent_id            14 non-null     object
 2   record_type          14 non-null     object
 3   category             0 non-null      float64
 4   pillar               14 non-null     object
 5   indicator            14 non-null     object
 6   indicator_code       0 non-null      float64
 7   indicator_direction  0 non-null      float64
 8   value_numeric        12 non-null     float64
 9   value_text           0 non-null      float64
 10  value_type           14 non-null     object
 11  unit                 14 non-null     object
 12  observation_date     14 non-null     datetime64[ns]
 13  period_start         0 non-null      float64
 14  period_end           0 non-null      float64
 15  fiscal_year          0 non-null      float64
 16  gender               14 non-null     object
 17  location             14 non-null     object
 18  region               0 non-null      float64
 19  source_name          0 non-null      float64
 20  source_type          0 non-null      float64
 21  source_url           0 non-null      float64
 22  confidence           14 non-null     object
 23  related_indicator    14 non-null     object
 24  relationship_type    14 non-null     object
 25  impact_direction     14 non-null     object
 26  impact_magnitude     14 non-null     object
 27  impact_estimate      12 non-null     float64
 28  lag_months           14 non-null     int64
 29  evidence_basis       14 non-null     object
 30  comparable_country   7 non-null      object
 31  collected_by         14 non-null     object
 32  collection_date      14 non-null     datetime64[ns]
 33  original_text        0 non-null      float64
 34  notes                14 non-null     object
dtypes: datetime64[ns](2), float64(14), int64(1), object(18)
memory usage: 4.0+ KB

,record_id,parent_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,IMP_0001,EVT_0001,impact_link,NaN,ACCESS,Telebirr effect on Account Ownership,NaN,NaN,15.0,NaN,...,increase,high,15.0,12,literature,Kenya,Example_Trainee,2025-01-20,NaN,Kenya M-Pesa showed +20pp over 5 years
1,IMP_0002,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on Telebirr Users,NaN,NaN,NaN,NaN,...,increase,high,NaN,3,empirical,NaN,Example_Trainee,2025-01-20,NaN,Direct subscriber acquisition
2,IMP_0003,EVT_0001,impact_link,NaN,USAGE,Telebirr effect on P2P Transactions,NaN,NaN,25.0,NaN,...,increase,high,25.0,6,empirical,NaN,Example_Trainee,2025-01-20,NaN,New digital payment channel
3,IMP_0004,EVT_0002,impact_link,NaN,ACCESS,Safaricom effect on 4G Coverage,NaN,NaN,15.0,NaN,...,increase,medium,15.0,12,empirical,NaN,Example_Trainee,2025-01-20,NaN,Network investment from competition
4,IMP_0005,EVT_0002,impact_link,NaN,AFFORDABILITY,Safaricom effect on Data Affordability,NaN,NaN,-20.0,NaN,...,decrease,medium,-20.0,12,literature,Rwanda,Example_Trainee,2025-01-20,NaN,Competition typically reduces prices

  parent_id         pillar   related_indicator impact_direction  lag_months
0  EVT_0001         ACCESS       ACC_OWNERSHIP         increase          12
1  EVT_0001          USAGE  USG_TELEBIRR_USERS         increase           3
2  EVT_0001          USAGE       USG_P2P_COUNT         increase           6
3  EVT_0002         ACCESS          ACC_4G_COV         increase          12
4  EVT_0002  AFFORDABILITY     AFF_DATA_INCOME         decrease          12

In [11]:
import pandas as pd
import numpy as np

# File paths (Windows-safe)
MAIN_FILE = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\ethiopia_fi_unified_data.xlsx"
REF_FILE = r"C:\Users\Kifiya_Administrator\Desktop\ethiopia-fi-forecast\ethiopia-fi-forecast\data\raw\reference_codes.xlsx"

In [12]:
# Inspect available sheets
xls = pd.ExcelFile(MAIN_FILE)
xls.sheet_names

['ethiopia_fi_unified_data', 'Impact_sheet']

In [13]:
# Load sheets by position (safe)
data = pd.read_excel(MAIN_FILE, sheet_name=xls.sheet_names[0])
impact_links = pd.read_excel(MAIN_FILE, sheet_name=xls.sheet_names[1])
refs = pd.read_excel(REF_FILE)

print("Data loaded successfully")

Data loaded successfully

In [14]:
data.info()

data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            43 non-null     object
 1   record_type          43 non-null     object
 2   category             10 non-null     object
 3   pillar               33 non-null     object
 4   indicator            43 non-null     object
 5   indicator_code       43 non-null     object
 6   indicator_direction  33 non-null     object
 7   value_numeric        33 non-null     float64
 8   value_text           10 non-null     object
 9   value_type           43 non-null     object
 10  unit                 33 non-null     object
 11  observation_date     43 non-null     datetime64[ns]
 12  period_start         10 non-null     datetime64[ns]
 13  period_end           10 non-null     datetime64[ns]
 14  fiscal_year          43 non-null     object
 15  gender               43 non-null     object
 16  location             43 non-null     object
 17  region               0 non-null      float64
 18  source_name          43 non-null     object
 19  source_type          43 non-null     object
 20  source_url           31 non-null     object
 21  confidence           43 non-null     object
 22  related_indicator    0 non-null      float64
 23  relationship_type    0 non-null      float64
 24  impact_direction     0 non-null      float64
 25  impact_magnitude     0 non-null      float64
 26  impact_estimate      0 non-null      float64
 27  lag_months           0 non-null      float64
 28  evidence_basis       0 non-null      float64
 29  comparable_country   43 non-null     object
 30  collected_by         43 non-null     datetime64[ns]
 31  collection_date      10 non-null     object
 32  original_text        33 non-null     object
 33  notes                0 non-null      float64
dtypes: datetime64[ns](4), float64(10), object(20)
memory usage: 11.6+ KB

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [15]:
# Record types
data['record_type'].value_counts()

# Pillar distribution
data['pillar'].value_counts(dropna=False)

# Source types
data['source_type'].value_counts()

# Confidence levels
data['confidence'].value_counts()

confidence
high      40
medium     3
Name: count, dtype: int64

In [16]:
# Unique indicators
data['indicator_code'].nunique(), data['indicator_code'].unique()

# Convert date column safely
data['observation_date'] = pd.to_datetime(
    data['observation_date'], errors='coerce'
)

# Temporal coverage
data['observation_date'].min(), data['observation_date'].max()

(Timestamp('2014-12-31 00:00:00'), Timestamp('2030-12-31 00:00:00'))

In [17]:
events = data[data['record_type'] == 'event']

events[['category', 'observation_date', 'source_name']].sort_values(
    'observation_date'
).head(10)

          category observation_date    source_name
33  product_launch       2021-05-17  Ethio Telecom
41          policy       2021-09-01            NBE
34    market_entry       2022-08-01           News
35  product_launch       2023-08-01      Safaricom
36  infrastructure       2024-01-01           NIDP
37          policy       2024-07-29            NBE
38       milestone       2024-10-01      EthSwitch
39     partnership       2025-10-27      EthSwitch
42         pricing       2025-12-15           News
40  infrastructure       2025-12-18  NBE/EthSwitch

In [18]:
impact_links.info()

impact_links.head()

impact_links[['parent_id', 'pillar', 'related_indicator',
              'impact_direction', 'impact_magnitude', 'lag_months']].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 35 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            14 non-null     object
 1   parent_id            14 non-null     object
 2   record_type          14 non-null     object
 3   category             0 non-null      float64
 4   pillar               14 non-null     object
 5   indicator            14 non-null     object
 6   indicator_code       0 non-null      float64
 7   indicator_direction  0 non-null      float64
 8   value_numeric        12 non-null     float64
 9   value_text           0 non-null      float64
 10  value_type           14 non-null     object
 11  unit                 14 non-null     object
 12  observation_date     14 non-null     datetime64[ns]
 13  period_start         0 non-null      float64
 14  period_end           0 non-null      float64
 15  fiscal_year          0 non-null      float64
 16  gender               14 non-null     object
 17  location             14 non-null     object
 18  region               0 non-null      float64
 19  source_name          0 non-null      float64
 20  source_type          0 non-null      float64
 21  source_url           0 non-null      float64
 22  confidence           14 non-null     object
 23  related_indicator    14 non-null     object
 24  relationship_type    14 non-null     object
 25  impact_direction     14 non-null     object
 26  impact_magnitude     14 non-null     object
 27  impact_estimate      12 non-null     float64
 28  lag_months           14 non-null     int64
 29  evidence_basis       14 non-null     object
 30  comparable_country   7 non-null      object
 31  collected_by         14 non-null     object
 32  collection_date      14 non-null     datetime64[ns]
 33  original_text        0 non-null      float64
 34  notes                14 non-null     object
dtypes: datetime64[ns](2), float64(14), int64(1), object(18)
memory usage: 4.0+ KB

,parent_id,pillar,related_indicator,impact_direction,impact_magnitude,lag_months
0,EVT_0001,ACCESS,ACC_OWNERSHIP,increase,high,12
1,EVT_0001,USAGE,USG_TELEBIRR_USERS,increase,high,3
2,EVT_0001,USAGE,USG_P2P_COUNT,increase,high,6
3,EVT_0002,ACCESS,ACC_4G_COV,increase,medium,12
4,EVT_0002,AFFORDABILITY,AFF_DATA_INCOME,decrease,medium,12

In [19]:
new_observation = {
    "record_type": "observation",
    "pillar": "access",
    "indicator": "Account ownership (female)",
    "indicator_code": "ACC_OWN_FEMALE",
    "value_numeric": 29.0,
    "observation_date": "2021-01-01",
    "source_name": "World Bank Global Findex",
    "source_url": "https://www.worldbank.org/globalfindex",
    "confidence": "high",
    "collected_by": "Kifiya",
    "collection_date": "2026-01-28",
    "notes": "Used for gender gap analysis"
}

data = pd.concat([data, pd.DataFrame([new_observation])], ignore_index=True)

In [20]:
new_event = {
    "record_type": "event",
    "category": "policy",
    "pillar": np.nan,
    "indicator": np.nan,
    "indicator_code": np.nan,
    "value_numeric": np.nan,
    "observation_date": "2020-12-01",
    "source_name": "National Bank of Ethiopia",
    "source_url": "https://nbe.gov.et",
    "confidence": "medium",
    "collected_by": "Kifiya",
    "collection_date": "2026-01-28",
    "notes": "Mobile money regulatory reform"
}

data = pd.concat([data, pd.DataFrame([new_event])], ignore_index=True)

In [21]:
new_impact_link = {
    "parent_id": "EVENT_NBE_MM_POLICY_2020",
    "pillar": "access",
    "related_indicator": "ACC_MM_ACCOUNT",
    "impact_direction": "positive",
    "impact_magnitude": 0.15,
    "lag_months": 12,
    "evidence_basis": "Observed post-policy growth"
}

impact_links = pd.concat(
    [impact_links, pd.DataFrame([new_impact_link])],
    ignore_index=True
)

In [22]:
# Save enriched datasets
data.to_csv(
    "../data/processed/ethiopia_fi_unified_data_enriched.csv",
    index=False
)

impact_links.to_csv(
    "../data/processed/impact_links_enriched.csv",
    index=False
)

print("Processed files saved successfully")

Processed files saved successfully

In [23]:
data.tail()

impact_links.tail()

,record_id,parent_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
10,IMP_0011,EVT_0007,impact_link,NaN,USAGE,M-Pesa Interop effect on M-Pesa Active Users,NaN,NaN,15.0,NaN,...,increase,medium,15.0,3,literature,Tanzania,Example_Trainee,2025-01-20,NaN,Tanzania interoperability increased usage +20%
11,IMP_0012,EVT_0007,impact_link,NaN,USAGE,M-Pesa Interop effect on P2P Count,NaN,NaN,10.0,NaN,...,increase,medium,10.0,3,literature,Tanzania,Example_Trainee,2025-01-20,NaN,Cross-platform transactions now possible
12,IMP_0013,EVT_0008,impact_link,NaN,USAGE,EthioPay effect on P2P Count,NaN,NaN,15.0,NaN,...,increase,medium,15.0,6,literature,India,Example_Trainee,2025-01-20,NaN,India UPI showed +25% volume increase
13,IMP_0014,EVT_0010,impact_link,NaN,AFFORDABILITY,Safaricom Price Hike effect on Data Affordability,NaN,NaN,10.0,NaN,...,increase,low,10.0,1,empirical,NaN,Example_Trainee,2025-01-20,NaN,Direct price increase (may be offset by switch...
14,NaN,EVENT_NBE_MM_POLICY_2020,NaN,NaN,access,NaN,NaN,NaN,NaN,NaN,...,positive,0.15,NaN,12,Observed post-policy growth,NaN,NaN,NaT,NaN,NaN